import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import random
from sklearn.metrics import mean_squared_error

def calculate_mape(y_true, y_pred):
    """Calculate Mean Absolute Percentage Error (MAPE)"""
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    non_zero_indices = y_true != 0
    return np.mean(np.abs((y_true[non_zero_indices] - y_pred[non_zero_indices]) / y_true[non_zero_indices])) * 100

# Konfigurasi halaman
st.set_page_config(
    page_title="Dashboard Monitoring Titik Panas Kabupaten Kuburaya",
    page_icon="🔥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Mapping tile ID to location names
TILE_LOCATION_MAP = {
    1: "Blok SK 1", 2: "Blok SK 2", 3: "Blok SK 3",
    4: "Blok SK 4", 5: "Blok SK 5",
    6: "Blok TP 1", 7: "Blok TP 2", 8: "Blok TP 3",
    9: "Blok TP 4", 10: "Blok TP 5",
    11: "Blok SR 1", 12: "Blok SR 2", 13: "Blok SR 3",
    14: "Blok SR 4", 15: "Blok SR 5",
    16: "Blok BA 1", 17: "Blok BA 2", 18: "Blok BA 3",
    19: "Blok BA 4", 20: "Blok BA 5",
    21: "Blok KB 1", 22: "Blok KB 2", 23: "Blok KB 3",
    24: "Blok KB 4", 25: "Blok KB 5"
}

# Fungsi untuk load data real
@st.cache_data
def load_real_data():
    """Load real data dari CSV files"""
    # Load historical data
    historical_df = pd.read_csv('monthly_hotspot_sum.csv')
    
    # Load forecast data from pipeline output
    forecast_df = pd.read_csv('data/forecasts/monthly_hotspot_forecasts_2025.csv')
    # Drop 'total' column generated by pipeline (not needed for per-tile processing)
    if 'total' in forecast_df.columns:
        forecast_df = forecast_df.drop(columns=['total'])
    
    # Load tile boundaries
    tiles_df = pd.read_csv('pontianak_tile_boundaries.csv')
    
    # Load real weather data from Kuburaya
    weather_df = pd.read_csv('Kuburaya Dalam angka 2014-2024.csv')
    
    # Clean weather data
    weather_df['Time'] = pd.to_datetime(weather_df['Time'])
    weather_df = weather_df.rename(columns={
        'Time': 'year_month',
        'penyinaran matahari': 'solar_radiation_raw',
        'avg kecepatan angin(knot)': 'wind_speed_knot',
        'arah angin terbanyak': 'wind_direction_raw',
        'curah hujan(mm)': 'rainfall_raw'
    })
    
    # Convert knots to m/s (1 knot = 0.514444 m/s)
    weather_df['wind_speed_ms'] = pd.to_numeric(weather_df['wind_speed_knot'], errors='coerce') * 0.514444
    
    # Clean rainfall data (remove commas and convert)
    weather_df['rainfall'] = weather_df['rainfall_raw'].astype(str).str.replace(',', '.').apply(pd.to_numeric, errors='coerce')
    
    # Clean solar radiation data
    weather_df['solar_radiation'] = pd.to_numeric(weather_df['solar_radiation_raw'], errors='coerce')
    
    # Convert solar radiation percentage to W/m² (approximate conversion)
    # Assuming max solar radiation ~1000 W/m² at 100%
    weather_df['solar_radiation_wm2'] = weather_df['solar_radiation'] * 10
    
    # Create weather lookup dict
    weather_lookup = {}
    for _, row in weather_df.iterrows():
        if pd.notna(row['year_month']):
            weather_lookup[row['year_month'].strftime('%Y-%m')] = {
                'rainfall': row['rainfall'] if pd.notna(row['rainfall']) else None,
                'solar_radiation': row['solar_radiation_wm2'] if pd.notna(row['solar_radiation_wm2']) else None,
                'wind_speed': row['wind_speed_ms'] if pd.notna(row['wind_speed_ms']) else None
            }
    
    # Create categorical risk lookup dynamically from forecast values
    # Using quartile thresholds computed from historical data per tile
    categorical_lookup = {}
    tile_cols = [f'tile_{i}' for i in range(1, 26)]
    
    # Compute per-tile quartile thresholds from historical data
    tile_thresholds = {}
    for tile_col in tile_cols:
        vals = historical_df[tile_col]
        nonzero_vals = vals[vals > 0]
        if len(nonzero_vals) > 0:
            tile_thresholds[tile_col] = {
                'q25': float(nonzero_vals.quantile(0.25)),
                'q75': float(nonzero_vals.quantile(0.75)),
            }
        else:
            tile_thresholds[tile_col] = {'q25': 0, 'q75': 0}
    
    for _, row in forecast_df.iterrows():
        year_month_key = pd.to_datetime(row['year_month']).strftime('%Y-%m')
        categorical_lookup[year_month_key] = {}
        for tile_num in range(1, 26):
            tile_col = f'tile_{tile_num}'
            val = row[tile_col]
            q25 = tile_thresholds[tile_col]['q25']
            q75 = tile_thresholds[tile_col]['q75']
            # Categorize: above Q75 = High, between Q25-Q75 = Medium, below Q25 = Low
            if val > q75 and q75 > 0:
                risk_level = 'Tinggi'
            elif val > q25 and q25 > 0:
                risk_level = 'Sedang'
            else:
                risk_level = 'Rendah'
            categorical_lookup[year_month_key][tile_num] = risk_level
    
    # Mark data sources before combining
    historical_df['sumber_data'] = 'Realisasi'
    forecast_df['sumber_data'] = 'prakiraan'
    
    # Combine historical/actual and forecast data
    combined_df = pd.concat([historical_df, forecast_df], ignore_index=True)
    
    # Convert to long format
    data_list = []
    for _, row in combined_df.iterrows():
        sumber = row.get('sumber_data', 'Realisasi')
        year_month = row['year_month']
        date = pd.to_datetime(year_month)
        year_month_key = date.strftime('%Y-%m')
        
        # Get month for season determination
        month = date.month
        is_dry_season = month in [4, 5, 6, 7, 8, 9, 10]
        
        # Get real weather data if available
        real_weather = weather_lookup.get(year_month_key, {})
        
        for tile_num in range(1, 26):  # 25 tiles
            tile_col = f'tile_{tile_num}'
            hotspot_count = row[tile_col]
            
            # Get tile info
            tile_info = tiles_df[tiles_df['id'] == tile_num].iloc[0]
            lat = (tile_info['lat_top_left'] + tile_info['lat_bottom_left']) / 2
            lon = (tile_info['lon_top_left'] + tile_info['lon_bottom_left']) / 2
            
            # Use location name mapping
            area_name = TILE_LOCATION_MAP.get(tile_num, f"Tile {tile_num}")
            
            # Use real weather data if available, otherwise simulate
            if real_weather.get('rainfall') is not None:
                # Use real data
                rainfall = real_weather['rainfall']
                solar_radiation = real_weather.get('solar_radiation')
                if solar_radiation is None:
                    solar_radiation = 450 if is_dry_season else 350
                    
                wind_speed = real_weather.get('wind_speed')
                if wind_speed is None:
                    wind_speed = 3.5 if is_dry_season else 2.8
                
                # Estimate temperature based on rainfall and season
                if is_dry_season:
                    temperature = 28 - (rainfall / 100) + np.random.normal(0, 0.5)
                else:
                    temperature = 27 - (rainfall / 150) + np.random.normal(0, 0.5)
                
                # Estimate humidity based on rainfall
                humidity = min(95, max(60, 75 + (rainfall / 20) + np.random.normal(0, 3)))
                
                # Wind direction based on season (real data often shows T/A - not available)
                if is_dry_season:
                    wind_direction = 120 + np.random.normal(0, 30)  # Southeast
                else:
                    wind_direction = 240 + np.random.normal(0, 30)  # Southwest
            else:
                # Simulate for 2025 or missing data
                if is_dry_season:
                    rainfall = max(0, 120 - hotspot_count * 10 + np.random.normal(0, 30))
                    temperature = 28 + hotspot_count * 0.1 + np.random.normal(0, 1)
                    humidity = max(60, 75 - hotspot_count * 0.5 + np.random.normal(0, 5))
                    solar_radiation = 450 + np.random.normal(0, 40)
                    wind_speed = 3.5 + np.random.normal(0, 1)
                    wind_direction = 120 + np.random.normal(0, 30)
                else:
                    rainfall = max(0, 280 - hotspot_count * 5 + np.random.normal(0, 50))
                    temperature = 27 + hotspot_count * 0.05 + np.random.normal(0, 1)
                    humidity = max(70, 85 - hotspot_count * 0.3 + np.random.normal(0, 5))
                    solar_radiation = 350 + np.random.normal(0, 40)
                    wind_speed = 2.8 + np.random.normal(0, 1)
                    wind_direction = 240 + np.random.normal(0, 30)
            
            wind_direction = wind_direction % 360
            
            # Ensure all values are numeric (not None)
            rainfall = rainfall if rainfall is not None else 0
            solar_radiation = solar_radiation if solar_radiation is not None else (450 if is_dry_season else 350)
            wind_speed = wind_speed if wind_speed is not None else (3.5 if is_dry_season else 2.8)
            temperature = temperature if temperature is not None else (28 if is_dry_season else 27)
            humidity = humidity if humidity is not None else (75 if is_dry_season else 85)
            
            # FFMC calculation
            ffmc = max(20, min(95, 60 + (hotspot_count * 2) - (rainfall * 0.1)))
            
            # Check if this is 2025 forecast data with categorical risk
            year = date.year
            if year == 2025 and year_month_key in categorical_lookup:
                # Use categorical risk from CSV
                risk_level = categorical_lookup[year_month_key].get(tile_num, 'Rendah')
                # Assign risk score based on categorical level
                if risk_level == 'Tinggi':
                    risk_score = 60  # High risk score
                elif risk_level == 'Sedang':
                    risk_score = 40  # Medium risk score
                else:
                    risk_score = 20  # Low risk score
            else:
                # Calculate risk for historical data
                risk_score = (
                    hotspot_count * 5 + 
                    max(0, (100 - rainfall/3)) * 0.25 +
                    max(0, (temperature - 26)) * 0.15 +
                    max(0, (ffmc - 40)) * 0.15 +
                    max(0, (wind_speed - 2)) * 0.10
                )
                
                if risk_score > 70:
                    risk_level = "Sangat Tinggi"
                elif risk_score > 50:
                    risk_level = "Tinggi"
                elif risk_score > 30:
                    risk_level = "Sedang"
                else:
                    risk_level = "Rendah"
            
            # ISPU calculation
            ispu = max(0, int(45 + (hotspot_count * 3) + np.random.normal(0, 10)))
            
            data_list.append({
                'tanggal': date,
                'area': area_name,
                'tile_id': tile_num,
                'latitude': lat,
                'longitude': lon,
                'titik_panas': hotspot_count,
                'curah_hujan': rainfall,
                'sinaran_matahari': solar_radiation,
                'kecepatan_angin': wind_speed,
                'arah_angin': wind_direction,
                'suhu': temperature,
                'kelembaban': humidity,
                'ffmc': ffmc,
                'ispu': ispu,
                'tingkat_risiko': risk_level,
                'skor_risiko': risk_score,
                'musim': 'Kemarau' if is_dry_season else 'Hujan',
                'sumber_data': sumber
            })
    
    return pd.DataFrame(data_list)

@st.cache_data
def load_validation_data():
    """Load data realisasi/aktual tahun 2025 untuk validasi"""
    try:
        # Membaca file CSV data asli 2025
        val_df = pd.read_csv('real_monthly_hotspot_sum2025.csv')
        
        # Mengubah format data dari lebar (wide) ke panjang (long) agar cocok dengan data forecast
        val_melted = val_df.melt(
            id_vars=['year_month'], 
            var_name='tile_str', 
            value_name='titik_panas_aktual'
        )
        
        # Membersihkan kolom tile_id (mengubah 'tile_1' menjadi angka 1)
        val_melted['tile_id'] = val_melted['tile_str'].str.replace('tile_', '').astype(int)
        
        # Mengubah format tanggal
        val_melted['tanggal'] = pd.to_datetime(val_melted['year_month'])
        
        return val_melted[['tanggal', 'tile_id', 'titik_panas_aktual']]
    except FileNotFoundError:
        return None

# Load real data
df = load_real_data()

# Page Navigation
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    ["Ringkasan Eksekutif", "Detail Data"]
)
st.sidebar.markdown("---")

# Filter Panel
st.sidebar.subheader("Panel Filter")

st.sidebar.info("""
    **Legenda Kode Blok:**
    - **SK** = Sungai Kakap
    - **TP** = Teluk Pakedai
    - **SR** = Sungai Raya
    - **BA** = Batu Ampar
    - **KB** = Kubu Raya
    """)
# Area filter

st.sidebar.markdown("""
<style>
    /* Limit multiselect height */
    div[data-baseweb="select"] > div {
        max-height: 100px;
        overflow-y: auto;
    }
    
    /* Style the selected items container */
    .stMultiSelect [data-baseweb="tag"] {
        font-size: 12px;
        padding: 2px 6px;
    }
</style>
""", unsafe_allow_html=True)

st.sidebar.markdown("**Filter Area/Lokasi**")
all_areas = sorted(df['area'].unique())
selected_areas = st.sidebar.multiselect(
    "Pilih Lokasi:",
    options=all_areas,
    default=all_areas
)

# Date range filter - Month based
st.sidebar.markdown("**Rentang Waktu**")
# Filter to show only 2020 onwards for more relevant data
years = sorted([y for y in df['tanggal'].dt.year.unique() if y >= 2020])
months = list(range(1, 13))
month_names = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
               'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']

# Default to last available year (single year view for correct YoY)
default_year = years[-1]  # Last available year (e.g. 2025)
default_start_idx = years.index(default_year)
default_end_idx = years.index(default_year)

col1, col2 = st.sidebar.columns(2)
with col1:
    start_year = st.selectbox("Tahun Awal:", years, index=default_start_idx)
    start_month = st.selectbox("Bulan Awal:", months, format_func=lambda x: month_names[x-1], index=0)
with col2:
    end_year = st.selectbox("Tahun Akhir:", years, index=default_end_idx)
    end_month = st.selectbox("Bulan Akhir:", months, format_func=lambda x: month_names[x-1], index=11)

# Apply filters
filtered_df = df.copy()

# Filter by areas
if selected_areas:
    filtered_df = filtered_df[filtered_df['area'].isin(selected_areas)]

# Filter by date range
start_date = pd.Timestamp(year=start_year, month=start_month, day=1)
end_date = pd.Timestamp(year=end_year, month=end_month, day=1) + pd.offsets.MonthEnd(0)
filtered_df = filtered_df[(filtered_df['tanggal'] >= start_date) & (filtered_df['tanggal'] <= end_date)]

# Calculate YoY metrics for comparison
prev_year_start = start_date - pd.DateOffset(years=1)
prev_year_end = end_date - pd.DateOffset(years=1)
prev_year_df = df[(df['tanggal'] >= prev_year_start) & (df['tanggal'] <= prev_year_end)]
if selected_areas:
    prev_year_df = prev_year_df[prev_year_df['area'].isin(selected_areas)]

# Separate historical/actual and forecast data based on source
historical_df = filtered_df[filtered_df['sumber_data'] == 'Realisasi']
realisasi_df = filtered_df[filtered_df['sumber_data'] == 'Realisasi']
forecast_df = filtered_df[filtered_df['sumber_data'] == 'prakiraan']

# ============================================================================
# PAGE: RINGKASAN EKSEKUTIF
# ============================================================================
if page == "Ringkasan Eksekutif":
    # Header
    st.title("Dashboard Forecasting Titik Panas Kabupaten Kuburaya")
    st.markdown("**Sistem Prakiraan dan Monitoring Titik Panas Kabupaten Kuburaya, Kalimantan Barat**")
    
    # Description and constraints
    st.info("""
    **Tentang Dashboard:**
    
    Dashboard ini menyediakan analisis dan prakiraan titik panas (hotspot) untuk Kabupaten Kuburaya menggunakan model LSTM (Long Short-Term Memory). 
    Dashboard dirancang untuk membantu pengambilan keputusan dalam mitigasi kebakaran lahan dan hutan.
    """)
    
    st.markdown("---")

    # KPI Cards - Realisasi vs Forecast comparison
    # Calculate realisasi metrics
    realisasi_filtered = filtered_df[filtered_df['sumber_data'] == 'Realisasi']
    forecast_filtered = filtered_df[filtered_df['sumber_data'] == 'prakiraan']
    
    has_realisasi = len(realisasi_filtered) > 0
    has_forecast = len(forecast_filtered) > 0
    
    # --- Row 1: Realisasi ---
    if has_realisasi:
        st.markdown("#### Data Realisasi")
        col1, col2, col3 = st.columns(3)
        
        with col1:
            total_realisasi = realisasi_filtered['titik_panas'].sum()
            prev_total_hotspots = prev_year_df[prev_year_df['sumber_data'] == 'Realisasi']['titik_panas'].sum()
            yoy_change = 0 if prev_total_hotspots == 0 else ((total_realisasi - prev_total_hotspots) / prev_total_hotspots) * 100
            
            st.metric(
                label="Total Titik Panas (Realisasi)",
                value=f"{total_realisasi:,.0f}",
                delta=f"{yoy_change:+.1f}% YoY" if prev_total_hotspots > 0 else "N/A"
            )

        with col2:
            monthly_real = realisasi_filtered.groupby('tanggal')['titik_panas'].sum()
            avg_realisasi = monthly_real.mean()
            prev_real = prev_year_df[prev_year_df['sumber_data'] == 'Realisasi']
            prev_avg = prev_real.groupby('tanggal')['titik_panas'].sum().mean() if len(prev_real) > 0 else 0
            yoy_avg = 0 if prev_avg == 0 else ((avg_realisasi - prev_avg) / prev_avg) * 100
            
            st.metric(
                label="Rata-rata per Bulan (Realisasi)",
                value=f"{avg_realisasi:.1f}",
                delta=f"{yoy_avg:+.1f}% YoY" if prev_avg > 0 else "N/A"
            )

        with col3:
            if len(monthly_real) > 0:
                max_month_real = monthly_real.idxmax()
                max_val_real = monthly_real.max()
                st.metric(
                    label="Bulan Puncak (Realisasi)",
                    value=max_month_real.strftime('%B %Y'),
                    delta=f"{max_val_real:,.0f} titik panas"
                )
    
    # --- Row 2: Forecast ---
    if has_forecast:
        st.markdown("#### Data Prakiraan (Forecast)")
        col1, col2, col3 = st.columns(3)
        
        with col1:
            total_forecast = forecast_filtered['titik_panas'].sum()
            # Delta: perbandingan forecast vs realisasi
            if has_realisasi and total_realisasi > 0:
                diff_pct = ((total_forecast - total_realisasi) / total_realisasi) * 100
                delta_text = f"{diff_pct:+.1f}% vs Realisasi"
            else:
                delta_text = "N/A"
            
            st.metric(
                label="Total Titik Panas (Forecast)",
                value=f"{total_forecast:,.0f}",
                delta=delta_text
            )

        with col2:
            monthly_fcast = forecast_filtered.groupby('tanggal')['titik_panas'].sum()
            avg_forecast = monthly_fcast.mean()
            if has_realisasi and avg_realisasi > 0:
                diff_avg_pct = ((avg_forecast - avg_realisasi) / avg_realisasi) * 100
                delta_avg_text = f"{diff_avg_pct:+.1f}% vs Realisasi"
            else:
                delta_avg_text = "N/A"
            
            st.metric(
                label="Rata-rata per Bulan (Forecast)",
                value=f"{avg_forecast:.1f}",
                delta=delta_avg_text
            )

        with col3:
            if len(monthly_fcast) > 0:
                max_month_fcast = monthly_fcast.idxmax()
                max_val_fcast = monthly_fcast.max()
                st.metric(
                    label="Bulan Puncak (Forecast)",
                    value=max_month_fcast.strftime('%B %Y'),
                    delta=f"{max_val_fcast:,.0f} titik panas"
                )

    st.markdown("---")

    # Combined Historical and Forecast Chart
    st.subheader("Tren Titik Panas: Data Historis vs Prakiraan")
    
    # Monthly aggregation
    monthly_historical = historical_df.groupby('tanggal').agg({
        'titik_panas': 'sum',
        'curah_hujan': 'mean'
    }).reset_index()
    
    monthly_forecast = forecast_df.groupby('tanggal').agg({
        'titik_panas': 'sum',
        'curah_hujan': 'mean'
    }).reset_index()
    
    # Calculate MAE from validation data for the error band
    mae_value = None
    validation_df_for_chart = load_validation_data()
    if validation_df_for_chart is not None and len(forecast_df) > 0:
        forecast_2025_chart = df[(df['tanggal'].dt.year == 2025) & (df['sumber_data'] == 'prakiraan')].copy()
        eval_chart_df = pd.merge(
            forecast_2025_chart,
            validation_df_for_chart,
            on=['tanggal', 'tile_id'],
            how='inner'
        )
        if selected_areas:
            eval_chart_df = eval_chart_df[eval_chart_df['area'].isin(selected_areas)]
        if len(eval_chart_df) > 0:
            monthly_eval_chart = eval_chart_df.groupby('tanggal').agg({
                'titik_panas_aktual': 'sum',
                'titik_panas': 'sum'
            }).reset_index()
            mae_value = np.mean(np.abs(
                monthly_eval_chart['titik_panas_aktual'] - monthly_eval_chart['titik_panas']
            ))
    
    # Combined chart
    fig_combined = go.Figure()
    
    # Historical data - solid line
    if len(monthly_historical) > 0:
        fig_combined.add_trace(go.Scatter(
            x=monthly_historical['tanggal'],
            y=monthly_historical['titik_panas'],
            mode='lines+markers',
            name='Realisasi (Historis)',
            line=dict(color='#1f77b4', width=2),
            marker=dict(size=6),
            hovertemplate='<b>Realisasi</b><br>Tanggal: %{x|%B %Y}<br>Titik Panas: %{y:,.0f}<extra></extra>'
        ))
    
    # Forecast data - dashed line with different color + MAE error band
    if len(monthly_forecast) > 0:
        # Add MAE shaded error band if MAE is available
        if mae_value is not None:
            upper_bound = monthly_forecast['titik_panas'] + mae_value
            lower_bound = (monthly_forecast['titik_panas'] - mae_value).clip(lower=0)
            
            # Upper bound (invisible line)
            fig_combined.add_trace(go.Scatter(
                x=monthly_forecast['tanggal'],
                y=upper_bound,
                mode='lines',
                name='Batas Atas (±MAE)',
                line=dict(width=0),
                showlegend=False,
                hovertemplate='<b>Batas Atas</b><br>Tanggal: %{x|%B %Y}<br>Titik Panas: %{y:,.0f}<extra></extra>'
            ))
            
            # Lower bound (invisible line) with fill to upper bound
            fig_combined.add_trace(go.Scatter(
                x=monthly_forecast['tanggal'],
                y=lower_bound,
                mode='lines',
                name=f'Rentang Error (±MAE = {mae_value:.1f})',
                line=dict(width=0),
                fill='tonexty',
                fillcolor='rgba(255, 127, 14, 0.2)',
                hovertemplate='<b>Batas Bawah</b><br>Tanggal: %{x|%B %Y}<br>Titik Panas: %{y:,.0f}<extra></extra>'
            ))
        
        fig_combined.add_trace(go.Scatter(
            x=monthly_forecast['tanggal'],
            y=monthly_forecast['titik_panas'],
            mode='lines+markers',
            name='prakiraan (Forecast)',
            line=dict(color='#ff7f0e', width=3, dash='dash'),
            marker=dict(size=8, symbol='diamond'),
            hovertemplate='<b>prakiraan</b><br>Tanggal: %{x|%B %Y}<br>Titik Panas: %{y:,.0f}<extra></extra>'
        ))
    
    fig_combined.update_layout(
        title="Perbandingan Data Realisasi dan prakiraan Titik Panas",
        xaxis_title="Periode",
        yaxis_title="Jumlah Titik Panas",
        height=500,
        hovermode='x unified',
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
    )
    
    st.plotly_chart(fig_combined, use_container_width=True)
    
    mae_note = ""
    if mae_value is not None:
        mae_note = f"\n    - **Area Oranye Transparan**: Rentang error berdasarkan MAE (±{mae_value:.1f} titik panas)"
    
    st.info(f"""
    **Interpretasi Grafik:**
    - **Garis Biru Solid**: Data real dari pengamatan satelit MODIS/VIIRS (termasuk data aktual 2025)
    - **Garis Oranye Putus-putus**: prakiraan model LSTM untuk periode mendatang{mae_note}
    - Pola musiman terlihat jelas dengan puncak pada bulan-bulan kemarau (Juli-Oktober)
    """)
    
    st.markdown("---")

    st.title("Evaluasi Akurasi Model Forecasting (2025)")
    st.markdown("**Perbandingan Data Prakiraan (Forecast) vs Realisasi (Aktual)**")
    
    # 1. Load Data
    validation_df = load_validation_data()
    
    if validation_df is None:
        st.error("File 'real_monthly_hotspot_sum2025.csv' tidak ditemukan. Mohon upload file tersebut.")
    else:
        # Ambil data forecast (prakiraan) khusus tahun 2025 dari dataset utama
        forecast_2025 = df[(df['tanggal'].dt.year == 2025) & (df['sumber_data'] == 'prakiraan')].copy()
        
        # Gabungkan (Merge) data Forecast dan Aktual berdasarkan Tanggal dan Lokasi
        eval_df = pd.merge(
            forecast_2025,
            validation_df,
            on=['tanggal', 'tile_id'],
            how='inner',
            suffixes=('_pred', '_act')
        )
        
        # Filter berdasarkan area yang dipilih di sidebar
        if selected_areas:
            eval_df = eval_df[eval_df['area'].isin(selected_areas)]
            
        if len(eval_df) > 0:
            # 2. Perhitungan Error berdasarkan agregasi bulanan (bukan per tile)
            # Agregasi per bulan - sum semua tile untuk setiap bulan
            monthly_eval = eval_df.groupby('tanggal').agg({
                'titik_panas_aktual': 'sum',  # Total aktual per bulan
                'titik_panas': 'sum'           # Total prediksi per bulan
            }).reset_index()
            
            y_true = monthly_eval['titik_panas_aktual']
            y_pred = monthly_eval['titik_panas']
            
            # Hitung MAE (Mean Absolute Error) - Rata-rata selisih mutlak
            mae = np.mean(np.abs(y_true - y_pred))
            
            # Hitung RMSE (Root Mean Square Error)
            # Rumus Excel: SQRT(SUMXMY2(D2:D13,C2:C13)/COUNT(D2:D13))
            # Equivalent: SQRT(SUM((Aktual - Prediksi)^2) / COUNT)
            n = len(y_true)
            rmse = np.sqrt(np.sum((y_true - y_pred) ** 2) / n)
            
            # Debug: tampilkan data agregasi bulanan
            # st.write("Data Agregasi Bulanan (Aktual vs Prediksi):")
            # st.write(monthly_eval[['tanggal', 'titik_panas_aktual', 'titik_panas']])
            
            # 3. Tampilkan KPI
            st.markdown("### Metrik Performa Model")
            col1, col2, col3 = st.columns(3)
            
            with col1:
                st.metric(
                    "RMSE (Tingkat Error)", 
                    f"{rmse:.2f}", 
                    help="Root Mean Square Error. Semakin KECIL semakin baik."
                )
            
            with col2:
            # rmse per tile (optional, can be added if needed)
                rmse_per_tile = np.sqrt(np.mean((eval_df['titik_panas_aktual'] - eval_df['titik_panas']) ** 2))
                st.metric(
                    "RMSE per Tile",
                    f"{rmse_per_tile:.2f}",
                    help="RMSE dihitung per tile, kemudian dirata-rata. Memberikan gambaran error rata-rata per lokasi."
                )
                
            with col3:
                st.metric(
                    "MAE (Rata-rata Selisih)", 
                    f"{mae:.2f} titik", 
                    help="Rata-rata selisih jumlah titik panas (prediksi vs aktual)."
                )
                
            st.markdown("---")
            
            st.info("""
            **Catatan Perhitungan RMSE:**
            RMSE (Root Mean Square Error) mengukur rata-rata akar kuadrat dari selisih antara nilai prediksi dan aktual.
            Semakin kecil nilai RMSE, semakin baik performa model.
            """)
            
        else:
            st.warning("Data untuk tahun 2025 tidak ditemukan dalam rentang filter yang dipilih.")

    # Map visualization
    st.subheader("Peta Distribusi Spasial Titik Panas")

    # Month selector for map
    if len(forecast_df) > 0:
        available_months_2025 = sorted(forecast_df['tanggal'].unique())
        
        col_map1, col_map2 = st.columns([3, 1])
        with col_map2:
            selected_map_month = st.selectbox(
                "Pilih Bulan:",
                options=available_months_2025,
                format_func=lambda x: x.strftime('%B %Y'),
                index=len(available_months_2025)-1
            )
        
        map_data = forecast_df[forecast_df['tanggal'] == selected_map_month]
    else:
        latest_date = filtered_df['tanggal'].max()
        map_data = filtered_df[filtered_df['tanggal'] == latest_date]
        selected_map_month = latest_date
    
    # Create map with better zoom settings
    fig_map = px.scatter_mapbox(
        map_data,
        lat='latitude',
        lon='longitude',
        size='titik_panas',
        color='tingkat_risiko',
        hover_name='area',
        hover_data=['titik_panas', 'tingkat_risiko'],
        color_discrete_map={
            'Rendah': '#2ecc71',
            'Sedang': '#f39c12', 
            'Tinggi': '#e74c3c',
            'Sangat Tinggi': '#c0392b'
        },
        title=f"Sebaran Risiko Titik Panas - {selected_map_month.strftime('%B %Y')}",
        mapbox_style="open-street-map",
        zoom=8.5,  # Adjusted for better view of entire region
        center={"lat": -0.35, "lon": 109.2},
        size_max=30
    )
    
    fig_map.update_layout(
        height=700,
        mapbox=dict(
            bearing=0,
            pitch=0
        )
    )
    
    st.plotly_chart(fig_map, use_container_width=True)

            

# ============================================================================
# PAGE: DETAIL DATA
# ============================================================================
elif page == "Detail Data":
    st.title("Detail Data Prakiraan Titik Panas 2025")
    st.markdown("**Analisis Detail dan Tabel Data Bulanan**")
    st.markdown("---")
    
    if len(forecast_df) > 0:
        st.subheader("Ringkasan Bulanan Prakiraan 2025")
        st.info(
            "**Catatan Sumber Data:**\n\n"
            "• **Titik Panas**: Hasil prakiraan model LSTM berdasarkan data historis MODIS/VIIRS 2014-2024\n\n"
            "• **Curah Hujan**: Data disimulasikan berdasarkan pola musiman historis Kabupaten Kuburaya. "
            "Simulasi menggunakan rata-rata curah hujan musim kemarau (~120 mm) dan musim hujan (~280 mm) "
            "dengan mempertimbangkan korelasi terhadap jumlah titik panas prakiraan.\n\n"
            "• **Kategori Risiko**: Dihitung berdasarkan threshold dari metode Quartile pada skor risiko prakiraan titik panas."
        )
        # Monthly summary with risk categorization
        monthly_summary = forecast_df.groupby('tanggal').agg({
            'titik_panas': 'sum',
            'curah_hujan': 'mean',
            'tingkat_risiko': lambda x: x.mode()[0] if len(x) > 0 else 'Rendah'
        }).reset_index()
        
        monthly_summary['Bulan'] = monthly_summary['tanggal'].dt.strftime('%B %Y')
        monthly_summary['Titik Panas'] = monthly_summary['titik_panas'].round(0).astype(int)
        monthly_summary['Curah Hujan (mm)'] = monthly_summary['curah_hujan'].round(1)
        monthly_summary['Kategori Risiko'] = monthly_summary['tingkat_risiko']
        
        # Get min and max values for conditional formatting
        min_val = monthly_summary['Titik Panas'].min()
        max_val = monthly_summary['Titik Panas'].max()
        
        # Display table with styling
        display_df = monthly_summary[['Bulan', 'Titik Panas', 'Curah Hujan (mm)', 'Kategori Risiko']].copy()
        
        # Apply conditional formatting using Styler
        def highlight_values(row):
            styles = [''] * len(row)
            if row['Titik Panas'] == min_val:
                styles[1] = 'background-color: #d4edda; color: #155724; font-weight: bold'
            elif row['Titik Panas'] == max_val:
                styles[1] = 'background-color: #f8d7da; color: #721c24; font-weight: bold'
            
            # Color code risk category
            if row['Kategori Risiko'] == 'Tinggi':
                styles[3] = 'background-color: #f8d7da; color: #721c24; font-weight: bold'
            elif row['Kategori Risiko'] == 'Sedang':
                styles[3] = 'background-color: #fff3cd; color: #856404; font-weight: bold'
            else:
                styles[3] = 'background-color: #d4edda; color: #155724; font-weight: bold'
            
            return styles
        
        styled_df = display_df.style.apply(highlight_values, axis=1)
        
        st.dataframe(styled_df, use_container_width=True, height=500)
        
        st.markdown("""
        **Legenda Tabel:**
        - 🟢 **Hijau**: Nilai terendah atau Risiko Rendah
        - 🔴 **Merah**: Nilai tertinggi atau Risiko Tinggi
        - 🟡 **Kuning**: Risiko Sedang
        """)
        
        st.markdown("---")
        
        # Detailed forecast chart
        st.subheader("Grafik Detail Prakiraan 2025")
        
        fig_detail = go.Figure()
        
        fig_detail.add_trace(go.Bar(
            x=monthly_summary['tanggal'],
            y=monthly_summary['titik_panas'],
            name='Prakiraan Titik Panas',
            marker=dict(
                color=monthly_summary['titik_panas'],
                colorscale='Reds',
                showscale=True,
                colorbar=dict(title="Jumlah")
            ),
            hovertemplate='<b>%{x|%B %Y}</b><br>Titik Panas: %{y:,.0f}<extra></extra>'
        ))
        
        fig_detail.update_layout(
            title="prakiraan Titik Panas per Bulan (2025)",
            xaxis_title="Bulan",
            yaxis_title="Jumlah Titik Panas",
            height=400,
            showlegend=False
        )
        
        st.plotly_chart(fig_detail, use_container_width=True)
        
        st.markdown("---")
        
        # Area-wise breakdown
        st.subheader("Breakdown per Lokasi")
        
        area_summary = forecast_df.groupby('area').agg({
            'titik_panas': 'sum',
            'tingkat_risiko': lambda x: x.mode()[0] if len(x) > 0 else 'Rendah'
        }).reset_index()
        
        area_summary = area_summary.sort_values('titik_panas', ascending=False)
        area_summary.columns = ['Lokasi', 'Total prakiraan Titik Panas (2025)', 'Kategori Risiko Dominan']
        area_summary['Total prakiraan Titik Panas (2025)'] = area_summary['Total prakiraan Titik Panas (2025)'].round(0).astype(int)
        
        st.dataframe(area_summary, use_container_width=True, height=400)
        
        
    else:
        st.warning("Data prakiraan 2025 tidak tersedia. Silakan sesuaikan filter rentang waktu.")
        st.info("Pilih tahun 2025 pada filter sidebar untuk melihat data prakiraan.")



# Footer
st.markdown("---")
# Sidebar info
st.sidebar.markdown("---")
st.sidebar.info(
    "**Informasi Dashboard**\n\n"
    "**Cakupan Data:**\n"
    "• 25 blok area Kabupaten Kuburaya\n"
    "• Historis: 2020-2024\n"
    "• prakiraan: 2025\n\n"
    "**Model:**\n"
    "• LSTM (Long Short-Term Memory)\n"
    "• Training: Data 2014-2024\n\n"
    "**Sumber Data:**\n"
    "• Titik panas: MODIS/VIIRS\n"
    "• Cuaca: Kuburaya Dalam Angka\n\n"
    "**Kategori Risiko:**\n"
    "🟢 Rendah\n"
    "🟡 Sedang\n"
    "🔴 Tinggi"
)
